//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCOTransactionServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", ConfigurationName="SCOTransactionServices.SCOAddToTrans_Port")]
    public interface SCOAddToTrans_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans:SCOAddToTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SCOTransactionServices.SCOAddToTransaction_Result> SCOAddToTransactionAsync(SCOTransactionServices.SCOAddToTransaction request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033435")]
    public partial class RootSCOAddToTransIN
    {
        
        private SCOAddToTransINItems[] sCOAddToTransINItemsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SCOAddToTransINItems", Order=0)]
        public SCOAddToTransINItems[] SCOAddToTransINItems
        {
            get
            {
                return this.sCOAddToTransINItemsField;
            }
            set
            {
                this.sCOAddToTransINItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033435")]
    public partial class SCOAddToTransINItems
    {
        
        private string entryTypeField;
        
        private string numberField;
        
        private string variantCodeField;
        
        private string barcodeField;
        
        private string uoMField;
        
        private decimal quantityField;
        
        private decimal amountField;
        
        private string currencyCodeField;
        
        private string entryStatusField;
        
        private int lineNoField;
        
        public SCOAddToTransINItems()
        {
            this.quantityField = ((decimal)(0.00m));
            this.amountField = ((decimal)(0.00m));
            this.lineNoField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntryType
        {
            get
            {
                return this.entryTypeField;
            }
            set
            {
                this.entryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VariantCode
        {
            get
            {
                return this.variantCodeField;
            }
            set
            {
                this.variantCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UoM
        {
            get
            {
                return this.uoMField;
            }
            set
            {
                this.uoMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EntryStatus
        {
            get
            {
                return this.entryStatusField;
            }
            set
            {
                this.entryStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LineNo
        {
            get
            {
                return this.lineNoField;
            }
            set
            {
                this.lineNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class PayItems
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class TaxItems
    {
        
        private string idField;
        
        private string descriptionField;
        
        private string[] taxGroupIDField;
        
        private decimal taxAmountField;
        
        private string[] taxRatePctField;
        
        private int itemLineNoField;
        
        public TaxItems()
        {
            this.taxAmountField = ((decimal)(0.00m));
            this.itemLineNoField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxGroupID", Order=2)]
        public string[] TaxGroupID
        {
            get
            {
                return this.taxGroupIDField;
            }
            set
            {
                this.taxGroupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxRatePct", Order=4)]
        public string[] TaxRatePct
        {
            get
            {
                return this.taxRatePctField;
            }
            set
            {
                this.taxRatePctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ItemLineNo
        {
            get
            {
                return this.itemLineNoField;
            }
            set
            {
                this.itemLineNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class PeriodicDiscount
    {
        
        private int lineNoField;
        
        private string periodicDiscountDescriptionField;
        
        public PeriodicDiscount()
        {
            this.lineNoField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LineNo
        {
            get
            {
                return this.lineNoField;
            }
            set
            {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PeriodicDiscountDescription
        {
            get
            {
                return this.periodicDiscountDescriptionField;
            }
            set
            {
                this.periodicDiscountDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class SaleItems
    {
        
        private string idField;
        
        private int lineNoField;
        
        private string descriptionField;
        
        private string[] voidedField;
        
        private decimal quantityField;
        
        private decimal priceWithVATField;
        
        private decimal priceField;
        
        private decimal netAmountField;
        
        private decimal vATAmountField;
        
        private string[] netAmountWithVATField;
        
        private string[] periodicDiscountAmountField;
        
        private string[] periodicDiscountPercentageField;
        
        private decimal lineDiscountAmountField;
        
        private decimal lineDiscountPercentageField;
        
        private string[] totalDiscountAmountField;
        
        private string[] totalPercentageLineField;
        
        private string unitOfMeasureField;
        
        private string[] scaleItemField;
        
        private string barcodeField;
        
        public SaleItems()
        {
            this.lineNoField = 0;
            this.quantityField = ((decimal)(0.00m));
            this.priceWithVATField = ((decimal)(0.00m));
            this.priceField = ((decimal)(0.00m));
            this.netAmountField = ((decimal)(0.00m));
            this.vATAmountField = ((decimal)(0.00m));
            this.lineDiscountAmountField = ((decimal)(0.00m));
            this.lineDiscountPercentageField = ((decimal)(0.00m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LineNo
        {
            get
            {
                return this.lineNoField;
            }
            set
            {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Voided", Order=3)]
        public string[] Voided
        {
            get
            {
                return this.voidedField;
            }
            set
            {
                this.voidedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal PriceWithVAT
        {
            get
            {
                return this.priceWithVATField;
            }
            set
            {
                this.priceWithVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal NetAmount
        {
            get
            {
                return this.netAmountField;
            }
            set
            {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal VATAmount
        {
            get
            {
                return this.vATAmountField;
            }
            set
            {
                this.vATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetAmountWithVAT", Order=9)]
        public string[] NetAmountWithVAT
        {
            get
            {
                return this.netAmountWithVATField;
            }
            set
            {
                this.netAmountWithVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodicDiscountAmount", Order=10)]
        public string[] PeriodicDiscountAmount
        {
            get
            {
                return this.periodicDiscountAmountField;
            }
            set
            {
                this.periodicDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodicDiscountPercentage", Order=11)]
        public string[] PeriodicDiscountPercentage
        {
            get
            {
                return this.periodicDiscountPercentageField;
            }
            set
            {
                this.periodicDiscountPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal LineDiscountAmount
        {
            get
            {
                return this.lineDiscountAmountField;
            }
            set
            {
                this.lineDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal LineDiscountPercentage
        {
            get
            {
                return this.lineDiscountPercentageField;
            }
            set
            {
                this.lineDiscountPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalDiscountAmount", Order=14)]
        public string[] TotalDiscountAmount
        {
            get
            {
                return this.totalDiscountAmountField;
            }
            set
            {
                this.totalDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalPercentageLine", Order=15)]
        public string[] TotalPercentageLine
        {
            get
            {
                return this.totalPercentageLineField;
            }
            set
            {
                this.totalPercentageLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScaleItem", Order=17)]
        public string[] ScaleItem
        {
            get
            {
                return this.scaleItemField;
            }
            set
            {
                this.scaleItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class Customer
    {
        
        private string idField;
        
        private string nameField;
        
        private string name2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class TransactionInfo
    {
        
        private string storeIdField;
        
        private string posTerminalField;
        
        private string transactionIDField;
        
        private string receiptIDField;
        
        private string staffIDField;
        
        private string statusField;
        
        private string[] lCYField;
        
        private decimal totalDiscountAmountField;
        
        private decimal totalTotalDiscountAmountField;
        
        private string[] totalPercentageField;
        
        private string[] grossAmountField;
        
        private string[] grossAmountWithVATField;
        
        private decimal netAmountField;
        
        private decimal netAmountWithVatField;
        
        private string[] balanceAmountField;
        
        private string[] balanceAmountWithVatField;
        
        private decimal noOfItemLinesField;
        
        private decimal noOfPaymentLinesField;
        
        private bool saleAsReturnSaleField;
        
        private int transIdField;
        
        public TransactionInfo()
        {
            this.transactionIDField = "{00000000-0000-0000-0000-000000000000}";
            this.totalDiscountAmountField = ((decimal)(0.00m));
            this.totalTotalDiscountAmountField = ((decimal)(0.00m));
            this.netAmountField = ((decimal)(0.00m));
            this.netAmountWithVatField = ((decimal)(0.00m));
            this.noOfItemLinesField = ((decimal)(0.00m));
            this.noOfPaymentLinesField = ((decimal)(0.00m));
            this.saleAsReturnSaleField = false;
            this.transIdField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PosTerminal
        {
            get
            {
                return this.posTerminalField;
            }
            set
            {
                this.posTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionID
        {
            get
            {
                return this.transactionIDField;
            }
            set
            {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReceiptID
        {
            get
            {
                return this.receiptIDField;
            }
            set
            {
                this.receiptIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StaffID
        {
            get
            {
                return this.staffIDField;
            }
            set
            {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LCY", Order=6)]
        public string[] LCY
        {
            get
            {
                return this.lCYField;
            }
            set
            {
                this.lCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal TotalDiscountAmount
        {
            get
            {
                return this.totalDiscountAmountField;
            }
            set
            {
                this.totalDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal TotalTotalDiscountAmount
        {
            get
            {
                return this.totalTotalDiscountAmountField;
            }
            set
            {
                this.totalTotalDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalPercentage", Order=9)]
        public string[] TotalPercentage
        {
            get
            {
                return this.totalPercentageField;
            }
            set
            {
                this.totalPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GrossAmount", Order=10)]
        public string[] GrossAmount
        {
            get
            {
                return this.grossAmountField;
            }
            set
            {
                this.grossAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GrossAmountWithVAT", Order=11)]
        public string[] GrossAmountWithVAT
        {
            get
            {
                return this.grossAmountWithVATField;
            }
            set
            {
                this.grossAmountWithVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal NetAmount
        {
            get
            {
                return this.netAmountField;
            }
            set
            {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal NetAmountWithVat
        {
            get
            {
                return this.netAmountWithVatField;
            }
            set
            {
                this.netAmountWithVatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BalanceAmount", Order=14)]
        public string[] BalanceAmount
        {
            get
            {
                return this.balanceAmountField;
            }
            set
            {
                this.balanceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BalanceAmountWithVat", Order=15)]
        public string[] BalanceAmountWithVat
        {
            get
            {
                return this.balanceAmountWithVatField;
            }
            set
            {
                this.balanceAmountWithVatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal NoOfItemLines
        {
            get
            {
                return this.noOfItemLinesField;
            }
            set
            {
                this.noOfItemLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal NoOfPaymentLines
        {
            get
            {
                return this.noOfPaymentLinesField;
            }
            set
            {
                this.noOfPaymentLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool SaleAsReturnSale
        {
            get
            {
                return this.saleAsReturnSaleField;
            }
            set
            {
                this.saleAsReturnSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int TransId
        {
            get
            {
                return this.transIdField;
            }
            set
            {
                this.transIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RootSCOAddToTransIN", Namespace="urn:microsoft-dynamics-nav/xmlports/x10033436")]
    public partial class RootSCOAddToTransIN1
    {
        
        private TransactionInfo[] transactionInfoField;
        
        private Customer[] customerField;
        
        private SaleItems[] saleItemsField;
        
        private PeriodicDiscount[] periodicDiscountField;
        
        private TaxItems[] taxItemsField;
        
        private PayItems[] payItemsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionInfo", Order=0)]
        public TransactionInfo[] TransactionInfo
        {
            get
            {
                return this.transactionInfoField;
            }
            set
            {
                this.transactionInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Order=1)]
        public Customer[] Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SaleItems", Order=2)]
        public SaleItems[] SaleItems
        {
            get
            {
                return this.saleItemsField;
            }
            set
            {
                this.saleItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodicDiscount", Order=3)]
        public PeriodicDiscount[] PeriodicDiscount
        {
            get
            {
                return this.periodicDiscountField;
            }
            set
            {
                this.periodicDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxItems", Order=4)]
        public TaxItems[] TaxItems
        {
            get
            {
                return this.taxItemsField;
            }
            set
            {
                this.taxItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayItems", Order=5)]
        public PayItems[] PayItems
        {
            get
            {
                return this.payItemsField;
            }
            set
            {
                this.payItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCOAddToTransaction", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", IsWrapped=true)]
    public partial class SCOAddToTransaction
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=0)]
        public string authInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=1)]
        public string receiptID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=2)]
        public SCOTransactionServices.RootSCOAddToTransIN sCOAddToTransINXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=3)]
        public SCOTransactionServices.RootSCOAddToTransIN1 sCOAddToTransOUTXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=4)]
        public string errorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=5)]
        public string responseCode;
        
        public SCOAddToTransaction()
        {
        }
        
        public SCOAddToTransaction(string authInfo, string receiptID, SCOTransactionServices.RootSCOAddToTransIN sCOAddToTransINXML, SCOTransactionServices.RootSCOAddToTransIN1 sCOAddToTransOUTXML, string errorText, string responseCode)
        {
            this.authInfo = authInfo;
            this.receiptID = receiptID;
            this.sCOAddToTransINXML = sCOAddToTransINXML;
            this.sCOAddToTransOUTXML = sCOAddToTransOUTXML;
            this.errorText = errorText;
            this.responseCode = responseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCOAddToTransaction_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", IsWrapped=true)]
    public partial class SCOAddToTransaction_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=0)]
        public string authInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=1)]
        public string receiptID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=2)]
        public SCOTransactionServices.RootSCOAddToTransIN sCOAddToTransINXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=3)]
        public SCOTransactionServices.RootSCOAddToTransIN1 sCOAddToTransOUTXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=4)]
        public string errorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SCOAddToTrans", Order=5)]
        public string responseCode;
        
        public SCOAddToTransaction_Result()
        {
        }
        
        public SCOAddToTransaction_Result(string authInfo, string receiptID, SCOTransactionServices.RootSCOAddToTransIN sCOAddToTransINXML, SCOTransactionServices.RootSCOAddToTransIN1 sCOAddToTransOUTXML, string errorText, string responseCode)
        {
            this.authInfo = authInfo;
            this.receiptID = receiptID;
            this.sCOAddToTransINXML = sCOAddToTransINXML;
            this.sCOAddToTransOUTXML = sCOAddToTransOUTXML;
            this.errorText = errorText;
            this.responseCode = responseCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SCOAddToTrans_PortChannel : SCOTransactionServices.SCOAddToTrans_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SCOAddToTrans_PortClient : System.ServiceModel.ClientBase<SCOTransactionServices.SCOAddToTrans_Port>, SCOTransactionServices.SCOAddToTrans_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SCOAddToTrans_PortClient() : 
                base(SCOAddToTrans_PortClient.GetDefaultBinding(), SCOAddToTrans_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SCOAddToTrans_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCOAddToTrans_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(SCOAddToTrans_PortClient.GetBindingForEndpoint(endpointConfiguration), SCOAddToTrans_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCOAddToTrans_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SCOAddToTrans_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCOAddToTrans_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SCOAddToTrans_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCOAddToTrans_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SCOTransactionServices.SCOAddToTransaction_Result> SCOAddToTransactionAsync(SCOTransactionServices.SCOAddToTransaction request)
        {
            return base.Channel.SCOAddToTransactionAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SCOAddToTrans_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SCOAddToTrans_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://lscentral:7047/BC252/WS/Samkaup/Codeunit/SCOAddToTrans?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SCOAddToTrans_PortClient.GetBindingForEndpoint(EndpointConfiguration.SCOAddToTrans_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SCOAddToTrans_PortClient.GetEndpointAddress(EndpointConfiguration.SCOAddToTrans_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            SCOAddToTrans_Port,
        }
    }
}
